# Конфигурация для детального профилирования RAG системы на 50 примерах
experiment:
  name: "rag_gpu_profiling_experiment"
  description: "Детальное профилирование RAG системы с временными метриками по компонентам"
  tags: ["rag", "gpu", "profiling", "performance", "bottleneck_analysis"]

# Настройки данных - используем полный датасет RAG Bench
data:
  input_path: "datasets/rag_bench/documents_for_rag.json"  # Полный датасет документов
  dataset_path: "datasets/rag_bench/qa_pairs_full.json"  # Все пары вопрос-ответ
  chunk_size: 2000  # Оптимальный размер чанков
  chunk_overlap: 400
  text_splitter: "recursive"

# Настройки датасетов
datasets:
  rag_bench:
    path: "datasets/rag_bench"
    documents_file: "documents_for_rag.json"
    qa_pairs_file: "qa_pairs_full.json"
    vector_db_path: "datasets/rag_bench/vector_db"

# Настройки моделей для RTX 3090 (стабильные модели)
models:
  # Эмбеддинг модель (проверенная многоязычная)
  embedding:
    name: "ai-forever/ru-en-RoSBERTa"
    device: "cuda"
    normalize_embeddings: true
    
  # Генеративная модель (стабильная RAG модель)
  generator:
    name: "BSC-LT/salamandra-7b-instruct"  # Используем проверенную модель
    device: "cuda"
    max_new_tokens: 512
    temperature: 0.7
    do_sample: true

# Настройки векторной базы
vector_store:
  type: "chroma"
  persist_directory: "datasets/rag_bench/vector_db"
  collection_name: "rag_bench_documents"

# Настройки ретривера (оптимизированные)
retriever:
  k: 8  # Количество документов для поиска
  search_type: "similarity"
  fetch_k: 25

# Настройки оценки - ТОЛЬКО 50 ПРИМЕРОВ для быстрого тестирования
evaluation:
  metrics:
    - "cosine_similarity"
    - "rouge"
    - "bleu"
    - "exact_match"
    - "length_ratio"
  batch_size: 4  # Оптимальный размер батча
  save_predictions: true
  max_samples: 10  # ТОЛЬКО 10 примеров для быстрого профилирования

# Настройки MLflow
mlflow:
  experiment_name: "RAG_GPU_Profiling_Experiments"
  tracking_uri: "file:./mlruns"
  log_artifacts: true
  log_models: true

# Настройки веб-интерфейса
web:
  interface: "gradio"
  port: 7860
  host: "0.0.0.0"
  share: false

# Настройки логирования
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/rag_gpu_profiling_experiment.log"
