# Конфигурация для гибридного поиска на GPU
# Объединяет семантический поиск и BM25 для максимального качества

# Настройки данных
data:
  input_path: "datasets/sberquad/documents_for_rag.json"
  dataset_path: "datasets/sberquad/qa_pairs.json"

# Настройки датасетов
datasets:
  sberquad:
    path: "datasets/sberquad"
    documents_file: "documents_for_rag.json"
    qa_pairs_file: "qa_pairs.json"
    vector_db_path: "datasets/sberquad/vector_db"

# Настройки моделей (оптимизированы для GPU)
models:
  # Эмбеддинг модель (самая мощная многоязычная)
  embedding:
    name: "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
    device: "cuda"
    normalize_embeddings: true
    
  # Генеративная модель (Saiga-7B для максимального использования GPU)
  generator:
    name: "IlyaGusev/saiga_llama3_8b"
    device: "cuda"
    torch_dtype: "float16"
    max_new_tokens: 30
    temperature: 0.7
    do_sample: false
    top_p: 0.9

# Настройки векторной базы
vector_store:
  type: "faiss"
  persist_directory: "datasets/sberquad/vector_db"

# Настройки текстового сплиттера
text_splitter:
  chunk_size: 1000  # Больший размер для GPU
  chunk_overlap: 100

# Настройки ретривера
retriever:
  search_type: "hybrid"  # Гибридный поиск
  k: 5  # Финальное количество документов

# Настройки гибридного поиска
hybrid_search:
  # Веса для комбинирования результатов
  semantic_weight: 0.8  # Больший вес семантического поиска на GPU
  bm25_weight: 0.2      # Меньший вес BM25
  
  # Количество документов от каждого метода
  semantic_k: 15        # Больше документов от семантического поиска
  bm25_k: 15           # Больше документов от BM25 поиска
  final_k: 5           # Финальное количество документов
  
  # Дополнительные настройки
  rerank: true         # Переранжирование результатов
  normalize_scores: true  # Нормализация скоров
  
  # Параметры BM25
  bm25_k1: 1.2         # Параметр k1 для BM25
  bm25_b: 0.75         # Параметр b для BM25

# Настройки оценки
evaluation:
  metrics:
    # === ГРУППА 1: МЕТРИКИ ГЕНЕРАЦИИ ===
    - "cosine_similarity"     # Косинусное сходство между ответом и эталоном
    - "rouge1"               # ROUGE-1 (перекрытие униграмм)
    - "rouge2"               # ROUGE-2 (перекрытие биграмм)
    - "rougeL"               # ROUGE-L (наибольшая общая подпоследовательность)
    - "length_ratio"         # Отношение длины ответа к эталону
    - "exact_match"          # Точное совпадение ответа с эталоном
    - "keyword_overlap"      # Перекрытие ключевых слов
    - "contains_ground_truth" # Содержит ли ответ эталонный текст
    - "ground_truth_contains_answer" # Содержит ли эталон ответ
    - "partial_match"        # Частичное совпадение
    - "answer_completeness"  # Полнота ответа
    - "information_density"  # Информационная плотность
    - "response_time"        # Время ответа
    
    # === ГРУППА 2: МЕТРИКИ ПРОИЗВОДИТЕЛЬНОСТИ ===
    - "retrieval_time"       # Время поиска документов
    - "generation_time"      # Время генерации ответа
    - "context_preparation_time" # Время подготовки контекста
    - "retrieved_docs_count" # Количество найденных документов
    - "context_length"       # Длина контекста
    - "answer_length"        # Длина ответа
    
    # === ГРУППА 3: МЕТРИКИ РЕТРИВЕРА ===
    - "retriever_precision"      # Точность ретривера (Precision@K)
    - "retriever_recall"         # Полнота ретривера (Recall@K)
    - "retriever_f1"            # F1-мера ретривера
    - "retriever_hit_rate"      # Hit Rate@K
    - "retriever_mrr"           # Mean Reciprocal Rank
    - "retriever_ndcg"          # Normalized DCG
    - "retriever_coverage"      # Покрытие релевантных документов
    - "retriever_diversity"     # Разнообразие извлеченных документов

# Настройки MLflow
mlflow:
  experiment_name: "RAG_Hybrid_GPU_Experiment"
  tracking_uri: "file:./mlruns"
  log_artifacts: true
  log_models: false

# Настройки логирования
logging:
  level: "INFO"
  file: "logs/rag_hybrid_gpu.log"
  console: true


